version: '3.9'
services:
  app:
    container_name: techfiesta
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    environment:
      DATABASE_URI: ${DB_URI}
    ports:
      - 5000:5000
    depends_on:
      - database

  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
